combine_control_expr = false
brace_style = "AlwaysNextLine"
fn_single_line = true
where_single_line = true
match_block_trailing_comma = true
max_width = 120
force_multiline_blocks = true
use_field_init_shorthand = true
blank_lines_upper_bound = 2
