[package]
name = "yabitcoin"
version = "0.0.0"
authors = ["AtsukiTak <takatomgoo@gmail.com>"]

[dependencies]
bitcoin = "0.14"

futures = "0.1"

log = "0.4"
env_logger = "0.5"
error-chain = "0.12"

[lib]
name = "libyabitcoin"
path = "src/lib/lib.rs"
