[package]
name = "bitcoin_observer"
version = "0.0.0"
authors = ["AtsukiTak <takatomgoo@gmail.com>"]

[dependencies]
bitcoin = "0.13"

log = "0.4"
error-chain = "0.12"

[[bin]]
name = "bitcoin_observer"
path = "src/bin/main.rs"

[lib]
name = "libbitcoin_observer"
path = "src/lib/lib.rs"
